"""empty message

Revision ID: 22029ea89869
Revises: 
Create Date: 2017-12-10 18:00:42.474615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22029ea89869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('req_status', sa.Enum('COMPLETED', 'ONGOING', 'WAITING', name='reqstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'driver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
