"""empty message

Revision ID: 5f26817f9db3
Revises: 4b52b975d520
Create Date: 2017-12-10 22:31:21.089134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f26817f9db3'
down_revision = '4b52b975d520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('picked_up', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'picked_up')
    op.drop_column('requests', 'completed_at')
    # ### end Alembic commands ###
